### DISCUSSION TITLE
在fly.io上部署RSSHub，并自动更新

### DISCUSSION THREAD

**Discussion by aaro-n** [DIYgod/RSSHub#12707] [Show and tell]
1. 在fly.io上部署教程：[方案二：自行维护 fly.toml](https://docs.rsshub.app/install/#bu-shu-dao-fly-io-fang-an-er-zi-xing-wei-hu-fly-toml)
2. 参考官方文档，使用Github Actions进行部署：[Continuous Deployment with Fly.io and GitHub Actions](https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/)
3. 确认步骤2可以正常工作后，修改Github Actions配置文件如下：
```
name: Fly Deploy
on:
  push:
    branches:
      - main
  schedule:
   # Github Actions默认使用UTC时间，在北京时间3点37分运行定时任务
    - cron:  '37 19 * * *' 
   workflow_dispatch:

env:
  CI: true

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```
已经验证过，定时任务可以运行。

**Comment by aaro-n** [comment]
部署在fly.io上并使用fly.io提供的redis缓存（Upstash Redis），可能redis缓存会有网络问题，会提示`could not send HTTP request to instance: connection error: timed out`，解决办法是换成其他redis服务商

**Comment by aaro-n** [comment]
使用Github Actions自动更新部署时，最好设置超时时间，否则可能会一直运行，这是示例
```
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    # 设置运行5分钟
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```
