### DISCUSSION TITLE
无法通过喜马拉雅路由收听付费节目，请大家帮忙看看

### DISCUSSION THREAD

**Discussion by eMUQI** [DIYgod/RSSHub#15133] [Q&A]
大家好，我最近在喜马拉雅购买了付费节目。想用rss的方式收听。

我根据 https://docs.rsshub.app/zh/deploy/config#%E5%96%9C%E9%A9%AC%E6%8B%89%E9%9B%85 的指南，配置了`XIMALAYA_TOKEN` 环境变量。按照这个教程获取cookie https://www.lanmitu.com/2245.html

但是当我访问对应路由时，依然提示`[该内容需付费]` ` 今天操作太频繁啦，可以明天再试试哦~`

不知道有没有人遇到过同样的问题？你们是怎么解决的？谢谢！

![image](https://github.com/DIYgod/RSSHub/assets/32332228/ec021d49-d20a-4515-a39f-2aef7f73e851)

**Comment by eMUQI** [comment]
docker配置如下：

```
version: '3.9'



services:

    rsshub:

        # two ways to enable puppeteer:

        # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled

        # * (consumes more disk space and memory) leave everything unchanged

        image: diygod/rsshub

        restart: always

        ports:

            - '1200:1200'

        environment:

            NODE_ENV: production

            CACHE_TYPE: redis

            REDIS_URL: 'redis://redis:6379/'

            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'  # marked

            XIMALAYA_TOKEN: 'cookie'

        depends_on:

            - redis

            - browserless  # marked



    browserless:  # marked

        image: browserless/chrome  # marked

        restart: always  # marked

        ulimits:  # marked

          core:  # marked

            hard: 0  # marked

            soft: 0  # marked



    redis:

        image: redis:alpine

        restart: always

        volumes:

            - redis-data:/data



volumes:

    redis-data:


```
