### DISCUSSION TITLE
Rsshub大量占用CPU的IO，把服务器直接卡死

### DISCUSSION THREAD

**Discussion by godcreator02** [DIYgod/RSSHub#15847] [Q&A] [answered]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
无
```

### 相关文档

https://rsshub.netlify.app/zh/install/

### 预期是什么？

今天才安装rsshub，预期能正常运行，占用500M内存以下，服务器也不会卡住

我参考docker compose里第一种安装方法，用`diygod/rsshub:chromium-bundled`镜像，也部署了redis，下面是我的docker-compose.yml文件(Cookie部分删掉了)
```
version: '3.9'

services:
    rsshub:
        # two ways to enable puppeteer:
        # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
        # * (consumes more disk space and memory) leave everything unchanged
        image: diygod/rsshub:chromium-bundled
        restart: always
        ports:
            - '1200:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'

            BILIBILI_COOKIE_**: 

            TWITTER_USERNAME: 
            TWITTER_PASSWORD: 
            TWITTER_COOKIE: 
        depends_on:
            - redis
        deploy:
            resources:
                limits:
                    cpus: '0.7'
                    memory: 500M
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - /opt/dockerapps/rsshub/redis-data:/data

volumes:
    redis-data:
```

### 实际发生了什么？

当我在freshrss里随便更新了几个订阅源之后，CPU的IO读直接拉满了，服务器变得非常卡，看系统状态是chrome在调用IO。过几分钟会恢复正常，但是这几分钟内服务器就基本处于不可用状态
![图片](https://github.com/DIYgod/RSSHub/assets/49720881/2c1387b1-ec46-4327-abc7-6f911e773a57)

### 部署

自建

### 部署相关信息

OS: Linux, Docker 最新版

### 额外信息

```shell
Git Hash: e4782dca
Git Date: Thu, 06 Jun 2024 15:50:08 GMT
Cache Duration: 300s
Request Amount: 21
Request Frequency: 1.278 times/minute
Cache Hit Ratio: 0.00%
ETag Matched Ratio: 0.00%
Health: 42.86%
Uptime: 0.27 hour(s)
Hot Routes: 12 /bilibili/user/dynamic/:uid/:routeParams?
4 /
Hot Paths: 5 /
2 /logo.png
2 /favicon.ico
1 /bilibili/user/dynamic/10119428
1 /bilibili/user/dynamic/942755
1 /bilibili/user/dynamic/604710494
1 /bilibili/user/dynamic/1119253352
1 /bilibili/user/dynamic/88461692
1 /bilibili/user/dynamic/436656378
1 /bilibili/user/dynamic/33826835
1 /bilibili/user/dynamic/1985127693
1 /bilibili/user/dynamic/491920203
1 /bilibili/user/dynamic/43584648
1 /bilibili/user/dynamic/11008987
1 /bilibili/user/dynamic/266765166
Hot Error Routes: 12 /bilibili/user/dynamic/:uid/:routeParams?
Hot Error Paths: 1 /bilibili/user/dynamic/10119428
1 /bilibili/user/dynamic/942755
1 /bilibili/user/dynamic/604710494
1 /bilibili/user/dynamic/1119253352
1 /bilibili/user/dynamic/88461692
1 /bilibili/user/dynamic/436656378
1 /bilibili/user/dynamic/33826835
1 /bilibili/user/dynamic/1985127693
1 /bilibili/user/dynamic/491920203
1 /bilibili/user/dynamic/43584648
1 /bilibili/user/dynamic/11008987
1 /bilibili/user/dynamic/266765166
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。
