### DISCUSSION TITLE
( Self Answer ) Bilibili feed 过多导致一直无法抓取

### DISCUSSION THREAD

**Discussion by Seele0oO** [DIYgod/RSSHub#16406] [Q&A] [answered]
我将 bilibili 关注全部转换为 rss 订阅，这导致 rsshub 无法正常为我提供服务，即是在添加了 bilibili cookies 也是如此。
我找到了解决方案，并在此记录。

**Comment by Seele0oO** [comment, marked as answer]
```yml
version: '3.9'

services:
    rsshub:
        image: diygod/rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
            PROXY_PROTOCOL: http
            PROXY_HOST: 1.1.1.1
            PROXY_PORT: 7890
            PROXY_URI: http://1.1.1.1:7890
            YOUTUBE_KEY: ${YOUTUBE_KEY}
            YOUTUBE_CLIENT_ID: ${YOUTUBE_CLIENT_ID}
            YOUTUBE_CLIENT_SECRET: ${YOUTUBE_CLIENT_SECRET}
            YOUTUBE_REFRESH_TOKEN: ${YOUTUBE_REFRESH_TOKEN}
            PIXIV_REFRESHTOKEN: ${PIXIV_REFRESHTOKEN}
            PIXIV_IMG_PROXY: ${PIXIV_IMG_PROXY}
            TWITTER_USERNAME: ${TWITTER_USERNAME}
            TWITTER_PASSWORD: ${TWITTER_PASSWORD}
            BILIBILI_COOKIE_1: ${BILIBILI_COOKIE_1}
        depends_on:
            - redis
            - browserless
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 256M
            restart_policy:
                condition: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:1200"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s

    browserless:
        image: browserless/chrome
        restart: always
        ulimits:
          core:
            hard: 0
            soft: 0
        deploy:
            replicas: 5
            resources:
                limits:
                    cpus: '1.00'
                    memory: 1024M
                reservations:
                    cpus: '0.50'
                    memory: 512M
            restart_policy:
                condition: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000"]
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: '0.25'
                    memory: 256M
                reservations:
                    cpus: '0.10'
                    memory: 128M
            restart_policy:
                condition: on-failure
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s

volumes:
    redis-data:
```

**直接复制的朋友注意修改 proxy 部分的配置。**

效果非常的好，但是需要时间体现。
我是用的 rss 客户端是 miniflux ，它会自动对 fetch 计划做均匀分布。
如果一次性对所有 bilibili feed 抓取，大约有 140/510 的机率出现错误，在使用上面的部署方式 12 小时后，错误率为 0/510 。
