### ISSUE TITLE
BiliBili 动态失效

### ISSUE THREAD

**Issue by KaiHuaDou** [DIYgod/RSSHub#16263]
### 路由地址

```routes
/bilibili/user/dynamic/:uid/:routeParams?
```

### 完整路由地址

```fullroutes
/bilibili/user/dynamic/2267573
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#up-%E4%B8%BB%E5%8A%A8%E6%80%81

### 预期是什么？

显示 RSS

### 实际发生了什么？

进入出错界面

### 部署

自建

### 部署相关信息

Linux: CentOS 3.9, Docker 26.1.4

### 额外信息

`docker-compose.yml`:
```yaml
services:
    rsshub:
        image: diygod/rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            BILIBILI_COOKIE_2093477911: "***FULL COOKIE***"
        depends_on:
            - redis

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data

volumes:
    redis-data:
```

```shell
Route requested: /bilibili/user/dynamic/2267573
Error message: Cannot read property '0' of null
Helpful Information to provide when opening issue: 
Path: /bilibili/user/dynamic/2267573
Node version: v14.18.1
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。
