### ISSUE TITLE
知乎抓取出现403错误

### ISSUE THREAD

**Issue by fenhaizi** [DIYgod/RSSHub#18758]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/people/activities/247b240ccc5a586767395bbae0bdac30
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#%E7%9F%A5%E4%B9%8E

### 预期是什么？

获得该用户的活动，包括但不限于赞同了文章、发布了文章、回答了问题、etc

### 实际发生了什么？

遇到403错误（即便包含了z_c0的cookies依然403）

### 部署

自建

### 额外信息

```shell
用自家家庭宽带（国内）部署的RSShub，遇到403错误（即便包含了z_c0的cookies依然403），用浏览器访问源地址，提示"请求参数异常，请升级客户端后重试。"（10003）
```

### 这不是重复的 issue

- [x] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by AntoineChn** [comment]
我也遇到了同样的问题。

```
Error Message:
FetchError: [GET] "https://www.zhihu.com/people/jia-ming-zi-34": 403 Forbidden
Route: /zhihu/people/activities/:id
Full Route: /zhihu/people/activities/jia-ming-zi-34
Node Version: v22.14.0
Git Hash: 0f43236c
Git Date: Fri, 04 Apr 2025 19:07:02 GMT
```

但是奇怪的是，用 Folo 订阅 `rsshub://zhihu/people/activities/jia-ming-zi-34` 就能正常抓取内容。

Folo 背后不也是 RSSHub 服务器么？为什么 Folo 能正常抓取呢？

**Comment by Solitus516** [comment]
同出错，最后一篇文章抓在了四月一号晚上三点半，我是一直使用了cookie的，放个屁股蹲一蹲解决办法

**Comment by fenhaizi** [comment]
看到两天前zhihu/utils.ts似乎被更新了，然而并没有修复这个问题

**Comment by jkryanchou** [comment]
Same issue, Is there any solutions on it? I need help

**Comment by harryqchen** [comment]
同样问题，求助

**Comment by Ch1llNoodle** [comment]
把 getSignedHeader 中的签名参数（比如 d_c0 和 __zse_ck）替换成从浏览器抓包获取的 Cookie 值后，接口可以正常访问。是不是可以判断utils模拟生成的签名或加密逻辑存在问题？
![Image](https://github.com/user-attachments/assets/c2773b37-2903-435e-b3ce-68b9669b3058)

**Comment by AntoineChn** [comment]
@Ch1llNoodle 厉害！！

但是我没有想明白，该如何修改 `docker-compose.yml` 文件呢？是要更改 `ZHIHU_COOKIES` 这个环境变量么？

**Comment by Ch1llNoodle** [comment]
> [@Ch1llNoodle](https://github.com/Ch1llNoodle) 厉害！！  厉害！ ！
> 
> 但是我没有想明白，该如何修改 `docker-compose.yml` 文件呢？是要更改 `ZHIHU_COOKIES` 这个环境变量么？

我没有弄清楚d_c0和__zse_ck之间的关系如何，按照输出来讲d_c0为空是可以正常运行的，但代码后面计算x-zse-96的部分好像又必须要有d_c0。
// calculate x-zse-96, refer to https://github.com/srx-2000/spider_collection/issues/18
    const xzse93 = '101_3_3.0';
    const f = `${xzse93}+${apiPath}+${dc0}`;
    const xzse96 = '2.0_' + g_encrypt(md5(f));

如果想要正常使用的话，可以在ZHIHU_COOKIES 这个环境变量下添加z_c0, __zse_ck, d_c0，中间用分号分隔

![Image](https://github.com/user-attachments/assets/c6ca4d62-df60-48f8-96f1-0e397c68f7f9)

**Comment by cortat3am** [comment]
docker-compose.yaml环境变量ZHIHU_COOKIES后面的值，填网页版抓取的cookie全部值，更新最新的rsshub镜像。再试试看。

**Comment by GrayXu** [comment]
一样的问题，配置了cookie后正常了

**Comment by AntoineChn** [comment]
#18718 @

**Comment by AntoineChn** [comment]
@Ch1llNoodle 

感谢回复，我尝试「添加z_c0, __zse_ck, d_c0，中间用分号分隔」还是无法抓取。你这样配置后，成功了么？

在尝试过「添加z_c0, __zse_ck, d_c0」不成功后，我又尝试将完整的 cookies 赋给 ZHIHU_COOKIES。但是还是无法抓取。

@GrayXu 

你说「一样的问题，配置了cookie后正常了」，你能详细说说，你是如何配置 ZHIHU_COOKIES 变量的么？

**Comment by Ch1llNoodle** [comment]
> @Ch1llNoodle 
> 
> 感谢回复，我尝试「添加z_c0, __zse_ck, d_c0，中间用分号分隔」还是无法抓取。你这样配置后，成功了么？
> 
> 在尝试过「添加z_c0, __zse_ck, d_c0」不成功后，我又尝试将完整的 cookies 赋给 ZHIHU_COOKIES。但是还是无法抓取。
> 
> @GrayXu 
> 
> 你说「一样的问题，配置了cookie后正常了」，你能详细说说，你是如何配置 ZHIHU_COOKIES 变量的么？
> 
> ---
> 
> 提前感谢

我是成功了的，具体如何配置取决于用的是哪一种部署方式，如果是Docker Compose部署可以参考这一片[文章](https://zhuanlan.zhihu.com/p/32074541992?utm_psn=1894220148308677270)

**Comment by AntoineChn** [comment]
> > [@Ch1llNoodle](https://github.com/Ch1llNoodle)
> > 感谢回复，我尝试「添加z_c0, __zse_ck, d_c0，中间用分号分隔」还是无法抓取。你这样配置后，成功了么？
> > 在尝试过「添加z_c0, __zse_ck, d_c0」不成功后，我又尝试将完整的 cookies 赋给 ZHIHU_COOKIES。但是还是无法抓取。
> > [@GrayXu](https://github.com/GrayXu)
> > 你说「一样的问题，配置了cookie后正常了」，你能详细说说，你是如何配置 ZHIHU_COOKIES 变量的么？
> > 
> > 提前感谢
> 
> 我是成功了的，具体如何配置取决于用的是哪一种部署方式，如果是Docker Compose部署可以参考这一篇[文章](https://zhuanlan.zhihu.com/p/32074541992?utm_psn=1894220148308677270)。 形如ZHIHU_COOKIES: "z_c0=xxx; d_c0=yyy; __zse_ck=zzz" 。 手动部署只需把: 换成=。 希望可以有所帮助。

结合你的指导，和回复链接指向的 [文章](https://zhuanlan.zhihu.com/p/32074541992)。我的 RSShub 终于可以重新抓取知乎文章了。

具体实践中，还是遇到了砍，与大家分享。

## 不成功的实践

在我的实践中，diygod/rsshub:chromium-bundled 加上 ZHIHU_COOKIES: "z_c0=xxx; d_c0=yyy; __zse_ck=zzz" 仍然不行。

## 成功的实践

将 diygod/rsshub:chromium-bundled 拆分成两个服务，也就是

- rsshub 服务使用 diygod/rsshub:latest 镜像
- browserless 使用 browserless/chrome:latest 镜像

拆分时，在 rsshub 服务中配置 ZHIHU_COOKIES: "z_c0=xxx; d_c0=yyy; __zse_ck=zzz"

这样，就能成功抓取知乎文章了。

注：这种拆分，正是官方 [Docker-compose](https://github.com/DIYgod/RSSHub/blob/master/docker-compose.yml) 的默认部署方法。

## 后续

我要继续观察一段时间，如果 ZHIHU_COOKIES 经常过期，需要更新。我可能需要参考 [文章](https://zhuanlan.zhihu.com/p/32074541992) 中的建议，部署个 https://github.com/easychen/CookieCloud 了。

**Comment by 9k001** [comment]
> > > [@Ch1llNoodle](https://github.com/Ch1llNoodle)
> > > 感谢回复，我尝试「添加z_c0, __zse_ck, d_c0，中间用分号分隔」还是无法抓取。你这样配置后，成功了么？
> > > 在尝试过「添加z_c0, __zse_ck, d_c0」不成功后，我又尝试将完整的 cookies 赋给 ZHIHU_COOKIES。但是还是无法抓取。
> > > [@GrayXu](https://github.com/GrayXu)
> > > 你说「一样的问题，配置了cookie后正常了」，你能详细说说，你是如何配置 ZHIHU_COOKIES 变量的么？
> > > 提前感谢
> > 
> > 
> > 我是成功了的，具体如何配置取决于用的是哪一种部署方式，如果是Docker Compose部署可以参考这一篇[文章](https://zhuanlan.zhihu.com/p/32074541992?utm_psn=1894220148308677270)。 形如ZHIHU_COOKIES: "z_c0=xxx; d_c0=yyy; __zse_ck=zzz" 。 手动部署只需把: 换成=。 希望可以有所帮助。
> 
> 结合你的指导，和回复链接指向的 [文章](https://zhuanlan.zhihu.com/p/32074541992)。我的 RSShub 终于可以重新抓取知乎了。
> 
> 十分感谢。
> 
> 具体实践中，还是遇到了问题，与大家分享。
> 
> ## 不成功的实践
> 在我的实践中，diygod/rsshub:chromium-bundled 加上 ZHIHU_COOKIES: "z_c0=xxx; d_c0=yyy; __zse_ck=zzz" 仍然不行。
> 
> ## 成功的实践
> 将 diygod/rsshub:chromium-bundled 拆分成两个服务，也就是
> 
> * rsshub 服务使用 diygod/rsshub:latest 镜像
> * browserless 使用 browserless/chrome:latest 镜像
> 
> 拆分时，在 rsshub 服务中配置 ZHIHU_COOKIES: "z_c0=xxx; d_c0=yyy; __zse_ck=zzz"
> 
> 这样，就能成功抓取知乎了。
> 
> 注：这种拆分，正是官方 [Docker-compose](https://github.com/DIYgod/RSSHub/blob/master/docker-compose.yml) 的默认部署方法。
> 
> ## 后续
> 我要继续观察一段时间，如果 ZHIHU_COOKIES 经常过期，需要更新。我可能需要参考 [文章](https://zhuanlan.zhihu.com/p/32074541992) 中的建议，部署个 https://github.com/easychen/CookieCloud 了。
> 
> 再次感谢 [@Ch1llNoodle](https://github.com/Ch1llNoodle) [@cortat3am](https://github.com/cortat3am) 、 [@GrayXu](https://github.com/GrayXu) 等几位朋友。

奇怪了，我按照你给的方法还是403。替换镜像，用完整的cookie 或者是用短的按照上述方法配置的Cookie 也还是不行。
同时，我重新启动了路由，也基本上刷新了本地ip了。
ps: 替换镜像，我知道要用无头浏览器并配置了相关设置。

**Comment by luke396** [comment]
我这儿目前的情况是：diygod/rsshub:latest+无头浏览器，还是 diygod/rsshub:chromium-bundled；部分cookie，还是全部的cookie；他们四个的任何组合，返回的仍然是403。

挂着不动，偶尔有几次是可以获取到内容的，但没发现什么规律。

我是部署在美国的一个小vps上，我也尝试了直连和美国代理的不同cookie，都是一样的403。

**Comment by AntoineChn** [comment]
@9k001 那我也想不明白为什么了。

要不，你试试我正在用的这一套镜像的版本？

---

下面是我的完整环境信息，以及部署用的 Docker Compose。

我的 RSShub 部署在了群晖上，J4125 CPU （amd64 架构）。

家庭网络。

docker-compose 如下：

一些参数的说明：
- 我的群晖 1200 端口被占了。所以将 rsshub 的端口改到 1220。这样部署完，RSShub 在这里 http:SERVER_IP:1220 
- 群晖上 rsshub 服务下的 healthcheck 会报错。所以我注释掉了。
- 我隐去了自己的 知乎 Cookies。请做对应修改
- 我隐去了 redis 的本地路径。请做对应地修改
- 我将镜像的 tag 换成了 sha256 的 Manifest digest。这样，下载到的镜像，就是和我一样的版本，不会有歧义。

```yaml
version: '3.8'
services:
  rsshub:
    # image: diygod/rsshub:latest
    image: diygod/rsshub@sha256:f9e214e3f6003e3638d8b34847d8941ff893cf9386a74669921720d8d1fb78e9
    container_name: rsshub-new
    restart: always
    ports:
      - '1220:1220'
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
      PORT: 1220
      PUPPETEER_WS_ENDPOINT: "ws://browserless:3000"
      ZHIHU_COOKIES: "知乎 cookies 在这里，要包含 z_c0=xxx; d_c0=yyy; __zse_ck=zzz"
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://localhost:1220/healthz"]
    #     interval: 30s
    #     timeout: 10s
    #     retries: 3
    depends_on:
      - redis
      - browserless

  browserless:
    # image: browserless/chrome
    image: browserless/chrome@sha256:3678a24595187a3916dc45b800c4fe962832b581227bbef193ae6f0ec5fbc14d
    container_name: rsshub-chrome-new
    restart: always
    ulimits:
      core:
        hard: 0
        soft: 0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/pressure"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    # image: redis:alpine
    image: redis@sha256:519f0189dfdee3bc0bad61fb265fe73d864b5c64020e6579ad48a45c49965635
    container_name: rsshub-redis-new
    volumes:
      - 本地路径:/data
    restart: always
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 5s
```

RSShub 的 Debug 信息

```text
Git Hash:[edf603fb](https://github.com/DIYgod/RSSHub/commit/edf603fb)
Git Date:Sat, 12 Apr 2025 14:11:44 GMT
Cache Duration:300s
Request Amount:17
Request Frequency:1.930 times/minute
Cache Hit Ratio:5.88%
ETag Matched Ratio:29.41%
Health:100.00%
Uptime:0.15 hour(s)
```

Docker 版本

```bash
docker --version
# Docker version 24.0.2, build 610b8d0

docker-compose --version
# Docker Compose version v2.20.1-6047-g6817716
```
