### ISSUE TITLE
酷安编辑精选路由抓取出来的结果是新鲜图文

### ISSUE THREAD

**Issue by RikkaBlue** [DIYgod/RSSHub#5524]
- 完整路由地址，包含所有必选与可选参数
`https://example.com/coolapk/tuwen?key=MyKey`

- 预期是什么
抓取酷安的精选图文

- 实际发生了什么
实际抓取内容为新鲜图文
```xml
<title>
<![CDATA[ 酷安 - 新鲜图文 ]]>
</title>
<link>https://www.coolapk.com/</link>
<atom:link href="https://example.com/coolapk/tuwen?key=Mykey" rel="self" type="application/rss+xml"/>
<description>
<![CDATA[ 酷安 - 新鲜图文 - Made with love by RSSHub(https://github.com/DIYgod/RSSHub) ]]>
</description>
<generator>RSSHub</generator>
<webMaster>i@diygod.me (DIYgod)</webMaster>
<language>zh-cn</language>
<lastBuildDate>Tue, 25 Aug 2020 08:58:14 GMT</lastBuildDate>
<ttl>5</ttl>
```
- 部署相关信息

* docker-compose.yaml
```yaml
version: '3'

services:
    rsshub:
        image: diygod/rsshub
        container_name: rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE:
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
        env_file:
            - ./rsshub.env
        depends_on:
            - browserless

    browserless:
        image: browserless/chrome
        restart: always
```

* rsshub.env
```env
HTTP_BASIC_AUTH_NAME=name
HTTP_BASIC_AUTH_PASS=password
ACCESS_KEY=MyKey
LOGGER_LEVEL=info
```

* nginx conf
```conf
server {
        listen 443 ssl;
        listen [::]:443           ssl;
        server_name example.com;

        ssl_certificate /etc/letsencrypt/live/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/privkey.pem;

        location / {
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass http://127.0.0.1:1200/;
                }
}
server {
    listen      80;
    listen [::]:80;
    server_name example.com;

    location / `{`
        rewrite ^ https://$host$request_uri? permanent;
    }
}
```

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |     Debian 10 Linux version 4.19.0-10-amd64     |
| Node version       |               |
| if Docker, version |      19.03.12         |

- 额外信息（日志、报错等）

* docker logs
```logs
➜  rsshub sudo docker logs -f rsshub

> rsshub@1.0.0 start /app
> node lib/index.js

info: Listening Port 1200
info: 🎉 RSSHub start! Cheers!
info: /coolapk/tuwen?key=MyKey, user IP: 
```
* nginx accees log
```log
GET /coolapk/tuwen?key=MyKey HTTP/1.1" 200 96601 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
```
