### ISSUE TITLE
代理配置报错：tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:7890

### ISSUE THREAD

**Issue by littlecorgi-twk** [DIYgod/RSSHub#7361]
自行配置的rssHub。地址：[https://rsshub.littlecorgi.top/](https://rsshub.littlecorgi.top/)

#### 路由地址（不包含参数）

```routes
https://rsshub.littlecorgi.top/
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
https://rsshub.littlecorgi.top/bbc/chinese
```

#### 预期是什么
显示BBC的rss

#### 实际发生了什么
访问`https://rsshub.littlecorgi.top/bbc/chinese`后报错：
错误信息如下：
```error
Route requested: /bbc/chinese
Error message: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:7890
```
![image](https://user-images.githubusercontent.com/20331307/114267017-1666b380-9a2c-11eb-9c82-1abb395f409a.png)

`127.0.0.1:7890`是我自行配置的clash http端口。我在终端中通过`curl www.google.com`可以获取到数据。并且暴露此端口后，在浏览器中通过外网ip和此端口配置代理可以访问google。
![image](https://user-images.githubusercontent.com/20331307/114267148-c2100380-9a2c-11eb-966f-1dcdebb39c13.png)

#### 部署相关信息
```yml
version: '3'

services:
    rsshub:
        image: diygod/rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
            PROXY_PROTOCOL: http
            PROXY_HOST: 127.0.0.1
            PROXY_PORT: 7890
        depends_on:
            - redis
            - browserless

    browserless:
        # See issue 6680
        image: browserless/chrome:1.43-chrome-stable
        restart: always

    redis:
        image: redis:alpine
        restart: always
        volumes:
```

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       centOS7        |
| if Docker, version |      Docker version 20.10.5, build 55c4c88         |
