### ISSUE TITLE
邮箱设置出问题（类似#7159，但是试过了没用）

### ISSUE THREAD

**Issue by jerrywcy** [DIYgod/RSSHub#7922]
#### 路由地址（不包含参数）

```routes
/mail/imap/jerrymonkeynj@163.com
```
（反正我都用来注册账号了也没什么要保密的了吧）
#### 完整路由地址，包含所有必选与可选参数

```fullroutes
路由: /mail/imap/:email
参数: email, 必选 - 邮箱账号
```

#### 相关文档地址

- https://docs.rsshub.app/other.html#you-xiang
- https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi

#### 预期是什么

返回邮件列表

#### 实际发生了什么
```
Route requested: /mail/imap/jerrymonkeynj@163.com
Error message: mails.reverse is not a function
```

我使用的是docker-compose
以下是docker-compose.yml内容
```yml
version: '3'
  
services:
    rsshub:
        image: diygod/rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            EMAIL_CONFIG_jerrymonkeynj.163.com: password=*****\&host=imap.163.com\&port=993 #就是在原来的里面加了这句
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
        depends_on:
            - redis
            - browserless

    browserless:
        # See issue 6680
        image: browserless/chrome:1.43-chrome-stable
        restart: always
        ulimits:
          core:
            hard: 0
            soft: 0

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data

volumes:
    redis-data:
```
我试过在password一栏填163邮箱本身的密码和163给的imap服务的密码，但是都没有用
#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       Ubuntu20.04        |
| Node version       |         v10.19.0      |
| if Docker, version |        Docker version 19.03.12, build 48a66213fe       |

- 额外信息（日志、报错等）
这简直和 #7159 一模一样，但是我按着他们说的方法改了一下，&和/&和\&都试过，都没用。
有可能是163邮箱本身的问题，如果是的话那就没办法了，我当场换邮箱
