### ISSUE TITLE
邮件配置问题

### ISSUE THREAD

**Issue by gzzen** [DIYgod/RSSHub#8064]
#### 路由地址（不包含参数）

```
/mail/imap/:email
```

#### 完整路由地址，包含所有必选与可选参数

```
/mail/imap/gzzen.ne****er@gmail.com
```

#### 相关文档地址

- https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi

#### 预期是什么
获取邮件列表

#### 实际发生了什么
```
Route requested: /mail/imap/gzzen.ne*****er@gmail.com
Error message: please config email password, host, port in .env file
```

#### 部署相关信息
以下是我在`docker-compose.yml`中的环境配置部分，最后一行是添加的邮件配置。
```
environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
            EMAIL_CONFIG_gzzen.ne*****er.gmail.com: 'password=******&host=imap.gmail.com&port=993'
```
已仔细阅读文档及其他相关issue，写法借鉴了 #7922 ，但还是无法使用。不包含`'`或者将`:`改为`=`（类似于 #5437）会导致`docker-compose up`命令报错。

在 #5083 中提及了`.env`，但我在根目录中没有找到这个文件，所以手动添加了一个，里面只有一行：`EMAIL_CONFIG_gzzen.ne*****er.gmail.com=password=******&host=imap.gmail.com&port=993`。目前没有报错。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |        Ubuntu 20.04.2 LTS       |
| Node version       |        6.14.4       |
| if Docker, version |              20.10.7 |

- 额外信息（日志、报错等）
无

**Comment by aidistan** [comment]
+1，同样的现象和报错，再额外提供一些信息：

1. 在 container 中用 `env` 查看环境变量，能够看到 `EMAIL_CONFIG_***`，说明不是 docker 的问题；
2. 在 *config.js* 文件中打印 `envs` 变量，看不到 `EMAIL_CONFIG_***` 这个 key，感觉和 node 启动时的环境变量处理有关。

---

临时解决办法和题主一样，手工在 container 里配置一个 *.env* 文件

**Comment by Maecenas** [comment]
这个Issue的原因应该是在于含有点（`.`）的环境变量命名不规范。使用 docker-compose 部署时，容器启动时访问不到这些环境变量（[验证](https://docs.docker.com/compose/compose-file/compose-file-v3/#command)），但容器启动后能访问到（[验证](https://docs.docker.com/compose/reference/exec/)）。
建议的解决方案是把环境变量命名中的点 `.` 都替换成下划线 `_`。

**Comment by Colin-XKL** [comment]
补充一些信息：  
> 不包含'或者将:改为=（类似于 #5437）会导致docker-compose up命令报错

出现错误的原因是，compose文件使用的yaml格式，对于`-` 开头的都是列表，格式为`- AAA=BBB` ，而开头不是-的连续几行，后面以冒号进行赋值的为字典，格式为`AAA: BBB`。参见[here](https://stackoverflow.com/questions/66853440/docker-compose-error-invalid-type-it-should-be-a-string) 。下面是一个简单的示例

```
LIST:
  - AAA=aaa
  - BBB=bbb
DICT:
  AAA: aaa
  BBB: bbb
```

不过即便是修正了这个错误，我本地测试邮箱的rss还是无法使用
难道目前只有容器内添加env文件这一种方法了吗😂
