### ISSUE TITLE
订阅github具体commit时，提示错误

### ISSUE THREAD

**Issue by duee** [DIYgod/RSSHub#8554]
#### 路由地址（不包含参数）

```routes
[[/github/file/CyC2018/CS-Notes/master/notes/%25E4%25BB%25A3%25E7%25A0%2581%25E5%258F%25AF%25E8%25AF%25BB%25E6%2580%25A7.md]()](https://github.com/CyC2018/CS-Notes/blob/master/notes/%E4%BB%A3%E7%A0%81%E5%8F%AF%E8%AF%BB%E6%80%A7.md)
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
/github/file/CyC2018/CS-Notes/master/notes/%25E4%25BB%25A3%25E7%25A0%2581%25E5%258F%25AF%25E8%25AF%25BB% 25E6%2580%25A7.md
```

#### 相关文档地址

- https://docs.rsshub.app/...

#### 实际发生了什么
![image](https://user-images.githubusercontent.com/11386482/142115574-83a5cb72-abe3-4d5c-aca7-9f5c27f8648b.png)
![image](https://user-images.githubusercontent.com/11386482/142121551-6fcfd4bc-1eb9-4978-8955-b4a7822054dd.png)
![image](https://user-images.githubusercontent.com/11386482/142121906-6c1595df-00f5-44e5-ba8a-1ff11cb7528a.png)
![image](https://user-images.githubusercontent.com/11386482/142122056-3d57eb0e-5e92-4418-8208-b5b50ec711a3.png)

#### 部署相关信息
官方内容，没有改动
```
version: '3'

services:
    rsshub:
        image: diygod/rsshub
        restart: always
        ports:
            - '1200:1200'
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: 'redis://redis:6379/'
            PUPPETEER_WS_ENDPOINT: 'ws://browserless:3000'
        depends_on:
            - redis
            - browserless

    browserless:
        # See issue 6680
        image: browserless/chrome:1.43-chrome-stable
        restart: always
        ulimits:
          core:
            hard: 0
            soft: 0

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - redis-data:/data

volumes:
    redis-data:
```

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |        centos 7.5       |
| Node version       |      v14.18.1         |
| if Docker, version |     docker-ce           |

- 额外信息（日志、报错等）
-
